### ISSUE TITLE
Problem installing the backend with python3.9

### ISSUE THREAD

**Issue by javiquinte** [iris-edu/yasmine-stationxml-editor#29]
Considering that #28 is still pending I tried to install the backend part, but I found some errors.
I wanted to ask if this can be installed with new versions of python.
I tried with 3.9 and found the following problem.

In the instructions for the backend it seems to be a missing step between 5 and 6.

5. Run pip install -r requirements.txt
6. Run yasmineapp.py syncdb upgrade heads

Namely, something like
```
pip install -e .
```

But if I try to run step 6, the database cannot be find.

$ python3.9 yasmineapp.py syncdb upgrade heads
Traceback (most recent call last):
  File "/home/javier/git/yasmine-stationxml-editor/backend/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2138, in _wrap_pool_connect
    return fn()
  File "/home/javier/git/yasmine-stationxml-editor/backend/env/lib/python3.9/site-packages/sqlalchemy/pool.py", line 328, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/javier/git/yasmine-stationxml-editor/backend/env/lib/python3.9/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/javier/git/yasmine-stationxml-editor/backend/env/lib/python3.9/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/home/javier/git/yasmine-stationxml-editor/backend/env/lib/python3.9/site-packages/sqlalchemy/pool.py", line 1229, in _do_get
    return self._create_connection()
  File "/home/javier/git/yasmine-stationxml-editor/backend/env/lib/python3.9/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/home/javier/git/yasmine-stationxml-editor/backend/env/lib/python3.9/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/home/javier/git/yasmine-stationxml-editor/backend/env/lib/python3.9/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/home/javier/git/yasmine-stationxml-editor/backend/env/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/javier/git/yasmine-stationxml-editor/backend/env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 392, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

```

**Comment by rcasey-earthscope** [comment]
Let's keep this issue up as I would like to see native python installation working again.
