### ISSUE TITLE
Support for NRL v2

### ISSUE THREAD

**Issue by rcasey-earthscope** [iris-edu/yasmine-stationxml-editor#42]
Description to come

**Comment by metempleton** [comment]
I'm testing Gillian's nrl_v2 branch of yasmine and I'd like to test the "integration issues that still need to be worked out" that you mention.  Can you include enough details about them for me to test them?  I can't tell what they are.  Thanks!

**Comment by rcasey-earthscope** [comment]
Hi Mary-   I'm in the middle of some CCP code at the moment, so not prepared to drive Yasmine to get to the spot in question.  However, I can best describe it by going through the steps to create a new station and channel, then use the NRL tooling to define your instrumentation.

While the component information is able to be retrieved from NRL v2, I don't think that they combine correctly.  Ian has been looking into this as well, but I don't see sign of any code commits to this branch thus far.

Let us know if you see what is going on, because I remember getting some errors popping up in putting together the instrumentation.  I think it has to do with the stage mismatch between sensor and datalogger, but I could be wrong.

**Comment by metempleton** [comment]
Thanks Rob - I've spent some time combining responses and didn't notice anything during fairly extensive response editing.  The stationXML validates both with yasmine and with our validator. It's not a drop everything emergency, but I'm interested in how to reproduce what you found when there's time.

**Comment by is-unavco** [comment]
Thank you Rob and Mary for the additional insights. I am in the process of tracking down and patching these "integration issues", but nothing has popped up in my first pass.  Mary, if you do happen to encounter any integration issues in your use of Yasmine please feel free to tag me when opening the ticket.

**Comment by metempleton** [comment]
Will do Ian - thanks!  

Though not a ticket, one thing I've resolved is that the difference between the way v1 and v2 handle stages is addressed properly in the nrl_v2 branch.  Maybe this can save you some time. I don't actually know what an "integration issue" is.

More generally, I've been filing issue tickets regarding the main branch for a few weeks now - #35-41 & #43 on.  These are also relevant to the nrl_v2 branch.

**Comment by rcasey-earthscope** [comment]
An 'integration' issue is where mashing two different softwares together doesn't function correctly or throws errors.   In this case, Yasmine and NRLv2.

	I don't know if we need to break out into different tasks, but to start off, let's go with the first use case and see if you reproduce the error I got:

	Open up Yasmine.  Create a new XML file and Add a New Network.

	A wizard should open up that has you create a Network, enter values in fields, goto Next.
	Create a station, enter values in fields, make it just 1 stream, goto Next.
	Now we're in the channel section.  Enter values in the fields, goto Next.
	Select NRL Library, goto Next.
	For the Datalogger selection, I did:  EQMET -> SMA -> 250 Hz
	I get a popup:  "An Error Ocurred:  Internal Server Error"

	There is an exception stack that appears in the terminal window that I launched from.  I'll share that in a separate comment.

**Comment by rcasey-earthscope** [comment]
<pre>
yasmine-backend   | 2024-03-01 22:02:18,791 - INFO - web - 200 GET /api/nrl/sensors/0?_dc=1709330538680 (172.18.0.2) 76.62ms
yasmine-backend   | INFO:tornado.access:200 GET /api/nrl/sensors/0?_dc=1709330538680 (172.18.0.2) 76.62ms
yasmine-backend   | 2024-03-01 22:02:18,868 - INFO - web - 200 GET /api/nrl/dataloggers/0?_dc=1709330538682 (172.18.0.2) 137.01ms
yasmine-backend   | INFO:tornado.access:200 GET /api/nrl/dataloggers/0?_dc=1709330538682 (172.18.0.2) 137.01ms
yasmine-backend   | 2024-03-01 22:03:31,417 - ERROR - web - Uncaught exception GET /api/nrl/datalogger/response/?_dc=1709330611373&keys=EQMet&keys=SMA&keys=250%20Hz (172.18.0.2)
yasmine-backend   | HTTPServerRequest(protocol='http', host='yasmine-backend:80', method='GET', uri='/api/nrl/datalogger/response/?_dc=1709330611373&keys=EQMet&keys=SMA&keys=250%20Hz', version='HTTP/1.1', remote_ip='172.18.0.2')
yasmine-backend   | Traceback (most recent call last):
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 68, in __init__
yasmine-backend   |     self.sensors = self._parse_ini(sensor_index)
yasmine-backend   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 129, in _parse_ini
yasmine-backend   |     cp = self._get_cp_from_ini(path)
yasmine-backend   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 320, in _get_cp_from_ini
yasmine-backend   |     with codecs.open(path, mode='r', encoding='UTF-8') as f:
yasmine-backend   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "<frozen codecs>", line 918, in open
yasmine-backend   | FileNotFoundError: [Errno 2] No such file or directory: '/opt/yasmine/data/_media/nrl/content/NRL/sensors/index.txt'
yasmine-backend   |
yasmine-backend   | During handling of the above exception, another exception occurred:
yasmine-backend   |
yasmine-backend   | Traceback (most recent call last):
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
yasmine-backend   |     result = await result
yasmine-backend   |              ^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/tornado/gen.py", line 780, in run
yasmine-backend   |     yielded = self.gen.throw(exc)
yasmine-backend   |               ^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/opt/yasmine/src/yasmine/app/handlers/base.py", line 79, in get
yasmine-backend   |     res = yield self.async_call(self.async_get, *args, **kwargs)
yasmine-backend   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/tornado/gen.py", line 767, in run
yasmine-backend   |     value = future.result()
yasmine-backend   |             ^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
yasmine-backend   |     result = self.fn(*self.args, **self.kwargs)
yasmine-backend   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/opt/yasmine/src/yasmine/app/handlers/base.py", line 63, in async_call
yasmine-backend   |     return func(*args, **kwargs)
yasmine-backend   |            ^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/opt/yasmine/src/yasmine/app/handlers/xml_nrl.py", line 57, in async_get
yasmine-backend   |     return self.helper.get_datalogger_response_str(self.get_arguments('keys'))
yasmine-backend   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/opt/yasmine/src/yasmine/app/helpers/nrl/nrl_helper.py", line 71, in get_datalogger_response_str
yasmine-backend   |     path = self._build_path(self.nrl.dataloggers, datalogger_keys)
yasmine-backend   |                             ^^^^^^^^
yasmine-backend   |   File "/opt/yasmine/src/yasmine/app/helpers/nrl/nrl_helper.py", line 118, in nrl
yasmine-backend   |     self._nrl = NRL(os.path.join(self.content_folder,'NRL'))
yasmine-backend   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 312, in __init__
yasmine-backend   |     super(self.__class__, self).__init__()
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 76, in __init__
yasmine-backend   |     self.sensors = self._parse_ini(sensor_index)
yasmine-backend   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 129, in _parse_ini
yasmine-backend   |     cp = self._get_cp_from_ini(path)
yasmine-backend   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 320, in _get_cp_from_ini
yasmine-backend   |     with codecs.open(path, mode='r', encoding='UTF-8') as f:
yasmine-backend   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "<frozen codecs>", line 918, in open
yasmine-backend   | FileNotFoundError: [Errno 2] No such file or directory: '/opt/yasmine/data/_media/nrl/content/NRL/sensor/index.txt'
yasmine-backend   | ERROR:tornado.application:Uncaught exception GET /api/nrl/datalogger/response/?_dc=1709330611373&keys=EQMet&keys=SMA&keys=250%20Hz (172.18.0.2)
yasmine-backend   | HTTPServerRequest(protocol='http', host='yasmine-backend:80', method='GET', uri='/api/nrl/datalogger/response/?_dc=1709330611373&keys=EQMet&keys=SMA&keys=250%20Hz', version='HTTP/1.1', remote_ip='172.18.0.2')
yasmine-backend   | Traceback (most recent call last):
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 68, in __init__
yasmine-backend   |     self.sensors = self._parse_ini(sensor_index)
yasmine-backend   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 129, in _parse_ini
yasmine-backend   |     cp = self._get_cp_from_ini(path)
yasmine-backend   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 320, in _get_cp_from_ini
yasmine-backend   |     with codecs.open(path, mode='r', encoding='UTF-8') as f:
yasmine-backend   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "<frozen codecs>", line 918, in open
yasmine-backend   | FileNotFoundError: [Errno 2] No such file or directory: '/opt/yasmine/data/_media/nrl/content/NRL/sensors/index.txt'
yasmine-backend   |
yasmine-backend   | During handling of the above exception, another exception occurred:
yasmine-backend   |
yasmine-backend   | Traceback (most recent call last):
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
yasmine-backend   |     result = await result
yasmine-backend   |              ^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/tornado/gen.py", line 780, in run
yasmine-backend   |     yielded = self.gen.throw(exc)
yasmine-backend   |               ^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/opt/yasmine/src/yasmine/app/handlers/base.py", line 79, in get
yasmine-backend   |     res = yield self.async_call(self.async_get, *args, **kwargs)
yasmine-backend   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/tornado/gen.py", line 767, in run
yasmine-backend   |     value = future.result()
yasmine-backend   |             ^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
yasmine-backend   |     result = self.fn(*self.args, **self.kwargs)
yasmine-backend   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/opt/yasmine/src/yasmine/app/handlers/base.py", line 63, in async_call
yasmine-backend   |     return func(*args, **kwargs)
yasmine-backend   |            ^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/opt/yasmine/src/yasmine/app/handlers/xml_nrl.py", line 57, in async_get
yasmine-backend   |     return self.helper.get_datalogger_response_str(self.get_arguments('keys'))
yasmine-backend   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/opt/yasmine/src/yasmine/app/helpers/nrl/nrl_helper.py", line 71, in get_datalogger_response_str
yasmine-backend   |     path = self._build_path(self.nrl.dataloggers, datalogger_keys)
yasmine-backend   |                             ^^^^^^^^
yasmine-backend   |   File "/opt/yasmine/src/yasmine/app/helpers/nrl/nrl_helper.py", line 118, in nrl
yasmine-backend   |     self._nrl = NRL(os.path.join(self.content_folder,'NRL'))
yasmine-backend   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 312, in __init__
yasmine-backend   |     super(self.__class__, self).__init__()
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 76, in __init__
yasmine-backend   |     self.sensors = self._parse_ini(sensor_index)
yasmine-backend   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 129, in _parse_ini
yasmine-backend   |     cp = self._get_cp_from_ini(path)
yasmine-backend   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "/usr/local/lib/python3.12/site-packages/obspy/clients/nrl/client.py", line 320, in _get_cp_from_ini
yasmine-backend   |     with codecs.open(path, mode='r', encoding='UTF-8') as f:
yasmine-backend   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yasmine-backend   |   File "<frozen codecs>", line 918, in open
yasmine-backend   | FileNotFoundError: [Errno 2] No such file or directory: '/opt/yasmine/data/_media/nrl/content/NRL/sensor/index.txt'
yasmine-backend   | 2024-03-01 22:03:31,446 - ERROR - web - 500 GET /api/nrl/datalogger/response/?_dc=1709330611373&keys=EQMet&keys=SMA&keys=250%20Hz (172.18.0.2) 38.35ms
yasmine-backend   | ERROR:tornado.access:500 GET /api/nrl/datalogger/response/?_dc=1709330611373&keys=EQMet&keys=SMA&keys=250%20Hz (172.18.0.2) 38.35ms
</pre>

**Comment by rcasey-earthscope** [comment]
Of note is that the sensors.json and dataloggers.json are found in /Users/rob/Desktop/yasmine/install_run_Jan_2024/yasmine-stationxml-editor-nrl_v2/data/_media/nrl.   I am able to make selections from a list, so the navigation is not a problem.  However, the call to /api/nrl/datalogger/response seems to not yield anything.

When looking at the nrlv2 diff, I note that it looks like the entire .zip file of NRLv2 is downloaded from the web service.  I guess this is fine for a first go, but I thought that Yasmine was going to call to the web service itself.  Is there some kind of initialization I need to do?

**Comment by metempleton** [comment]
Thanks Rob!

My installation must be different, as I succeeded getting the EQMet SMA 250 Hz response with this console message:

yasmine-backend   | 2024-03-01 22:47:55,154 - INFO - web - 200 GET /api/nrl/datalogger/response/?_dc=1709333274755&keys=EQMet&keys=SMA&keys=250%20Hz (172.18.0.2) 388.14ms
yasmine-backend   | INFO:tornado.access:200 GET /api/nrl/datalogger/response/?_dc=1709333274755&keys=EQMet&keys=SMA&keys=250%20Hz (172.18.0.2) 388.14ms

FWIW, Gillian's branch pulls the full cached .zip file from the NRL ws and this takes time (X min?) to download and unzip.  But it only does this once per day; I'm not sure what time.  If yasmine is pulling a fresh copy, you'll need to wait until the following  "docker-compose up" console message reads:

yasmine-backend   | INFO:yasmine.app.helpers.nrl.nrl_helper:Creating an NRL key files

before proceeding, and there is nothing to tell you that this needs to be done currently.

You can also check whether the NRL has completed downloading by listing yasmine-stationxml-editor/data/_media/nrl/content/NRL - the datalogger and sensor dirs.

**Comment by gillian-earthscope** [comment]
The full console messages are:

yasmine-backend   | INFO:yasmine.app.helpers.nrl.nrl_helper:Unzipping NRL

yasmine-backend   | INFO:yasmine.app.helpers.nrl.nrl_helper:NRL has been
unzipped

yasmine-backend   | INFO:yasmine.app.helpers.nrl.nrl_helper:Creating an NRL
key files

yasmine-backend   | INFO:yasmine.app.helpers.nrl.nrl_helper:*NRL key files
have been created*


It should start the download when you start running the docker container.


Yes, we will want Yasmine to use the web service when possible but
replacing the NRL version 1 zip file download with version 2 was the
easiest way to get started working with version 2. As far as I know, Omid
is still working on a Python library for using the NRL web service.


cheers,

Gillian

**Comment by gillian-earthscope** [comment]
One issue is that if you had the NRL previously downloaded, you can work
with Yasmine immediately but when it starts unpacking the new download
while you are working then you'll start getting errors. The other of course
if you don't have a copy initially, you get errors right away and it's not
obvious that you have to wait 10+ minutes before it will be useable.

-Gillian

**Comment by rcasey-earthscope** [comment]
Thanks for the feedback everyone.  I'll see if I can get the NRL content to update and see if that addresses the issue.

	All of these behaviors are something we should document or improve.  I'll add a new issue to the project space regarding the fact that I can't tell when Yasmine is actually up and ready, since the logging to the screen is so cryptic.

	I miss the good old days when we were able to launch code from an icon (cross-platform).


	-Rob

**Comment by rcasey-earthscope** [comment]
I was able to get through the NRL steps with only a minor hitch.  Apparently I had a warning in the text window (and not in the UI).

	 WARNING (norm_resp): computed and reported sensitivities differ by more than 5 percent.

	I now somehow got myself stuck on the last page where I can save the results to the network user library, the station user library, and the channel user library.  When I hit Complete Wizard, it pops up an error and asks me to select a user library.  I can select all checkboxes, I can select one, doesn't matter.  If I roll back in the wizard and move forward again, same thing.  I've now got myself trapped.  If I reload the page, it will remove everything I did and I have to start over again.   Looks like I have more issues to file.

	However, I think that the NRL integration issue is dealt with.  If Mary's tests show that its valid response, then we may not have more of this NRL issue to address.  We're done with it, right?

	-Rob

**Comment by rcasey-earthscope** [comment]
Since the NRL v2 download of the zip file is working, we want to review that NRL navigation is functioning correctly and that responses are being generated properly.

**Comment by petrrr** [comment]
I believe this should have been implemenrted by  https://github.com/iris-edu/yasmine-stationxml-editor/pull/55.

So can we close this issue?

BTW: What about wrapping up a new release including this feature?
